### ISSUE TITLE
TI Parts out of stock for ~1 year

### ISSUE THREAD

**Issue by rbrenesh** [joeltroughton/uSMU#1]
Didn't really know if this should be an "issue" since it's out of your control but I thought I would bring it to your attention. We got a few of the boards made but haven't completed them since most TI parts, specifically the ones below, are out of stock and have lead times of about 1 year.

Out of stock parts with long lead times:
- PGA281AIPWR
- TPS65131RGET
- ADS1115IDGSR

**Comment by joeltroughton** [comment]
Unfortunately the global chip shortage is hitting all hardware projects hard. Grey market resellers (AliExpress) have all these ICs available for fairly reasonable prices, so I'd recommend using those until supply gets back to normal, or modify the design with more available ICs

**Comment by joeltroughton** [comment]
TPS65131 and ADS1115 are back in stock at LCSC

**Comment by rbrenesh** [comment]
![PXL_20220121_232048451](https://user-images.githubusercontent.com/33428877/150612462-a70cb397-c305-4bbe-94a7-68033aadf8c9.jpg)

Got some of them made with some grey market reseller parts. I'll flash them and calibrate them and we'll see how it goes!
